# Generated by Django 4.1.1 on 2022-09-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_passwordstorage_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordstorage',
            options={'ordering': ['user'], 'verbose_name': 'Password', 'verbose_name_plural': 'Passwords'},
        ),
        migrations.AlterField(
            model_name='passwordstorage',
            name='password',
            field=models.CharField(help_text='Write you password, max length 128 chars', max_length=128),
        ),
    ]
